apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admission.fullname" . }}
  labels:
    {{- include "admission.labels" . | nindent 4 }}
data:
  namespaces.exempt:
    {{- with .Values.namespaces.exempt }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
