apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "admission.fullname" . }}
  labels:
    {{- include "admission.labels" . | nindent 4 }}
webhooks:
- name: {{ .Values.mutatingWebhook.name }}
  admissionReviewVersions: ["v1"]
  sideEffects: {{ .Values.mutatingWebhook.sideEffects }}
  timeoutSeconds: {{ .Values.mutatingWebhook.timeoutSeconds }}
  reinvocationPolicy: {{ .Values.mutatingWebhook.reinvocationPolicy }}
  clientConfig:
    service:
      name: {{ include "admission.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate
    caBundle: {{ .Values.secrets.certificate.ca | b64enc }}
  rules:
  {{- with .Values.mutatingWebhook.rules }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
