apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admission.fullname" . }}
  labels:
    {{- include "admission.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.secrets.certificate.crt | b64enc }}
  tls.key: {{ .Values.secrets.certificate.key | b64enc }}
