---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: docker.io/steveszabo/webapp:v1.1.2
        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 100m
            memory: 64M
