---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-01
        image: docker.io/steveszabo/webapp:v1.1.2
        command: ["/bin/bash", "-c", "while true; do date; sleep 1; done"]
        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 100m
            memory: 64M
      - name: webapp-02
        image: docker.io/steveszabo/webapp:v1.1.2
        command: ["/bin/bash", "-c", "while true; do date; sleep 1; done"]
        resources:
          requests:
            cpu: 100m
            memory: 64M
          limits:
            cpu: 100m
            memory: 64M
