---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admission
data:
  namespaces.exempt: |
    base-actions-arc-google
    base-actions-controller
    base-admission
    base-argocd
    base-metrics-server
    base-terraform-agents
    base-terraform-operator
    kube-node-lease
    kube-public
    kube-system
  images.allowed: |
    docker.io/steveszabo/webapp:v1.1.0
    docker.io/steveszabo/webapp:v1.1.1
    docker.io/steveszabo/webapp:v1.1.2

---
apiVersion: v1
kind: Service
metadata:
  name: admission
spec:
  type: ClusterIP
  selector:
    app: admission
  ports:
  - name: admission
    protocol: TCP
    port: 443
    targetPort: 8443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admission
  template:
    metadata:
      labels:
        app: admission
    spec:
      volumes:
      - name: admission-configmap
        configMap:
          name: admission
          items:
          - key: namespaces.exempt
            path: namespaces.exempt
          - key: images.allowed
            path: images.allowed
      - name: admission-secret
        secret:
          secretName: admission
      containers:
      - name: admission
        image: docker.io/steveszabo/admission:v1.0.28
        ports:
        - name: admission
          containerPort: 8443
        env:
        - name: ADMISSION_ALLOW_IMAGES
          value: "/app/config/images.allowed"
        - name: ADMISSION_EXEMPT_NAMESPACES
          value: "/app/config/namespaces.exempt"
        - name: ADMISSION_CRT
          value: "/app/ssl/admission.base-admission.svc.crt"
        - name: ADMISSION_KEY
          value: "/app/ssl/admission.base-admission.svc.key"
        - name: ADMISSION_BIND
          value: "0.0.0.0:8443"
        - name: ADMISSION_WORKERS
          value: "1"
        - name: ADMISSION_THREADS
          value: "25"
        - name: ADMISSION_TIMEOUT
          value: "15"
        - name: ADMISSION_KEEP_ALIVE
          value: "15"
        - name: ADMISSION_LOG_LEVEL
          value: "debug"
#        - name: ADMISSION_AUDIT_MODE
#          value: "true"
        volumeMounts:
        - name: admission-configmap
          mountPath: /app/config
          readOnly: true
        - name: admission-secret
          subPath: tls.crt
          mountPath: /app/ssl/admission.base-admission.svc.crt
          readOnly: true
        - name: admission-secret
          subPath: tls.key
          mountPath: /app/ssl/admission.base-admission.svc.key
          readOnly: true
#        livenessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 5
#          successThreshold: 1
#          failureThreshold: 3
#          httpGet:
#            path: /health
#            port: admission
#            scheme: HTTPS
#        readinessProbe:
#          initialDelaySeconds: 5
#          periodSeconds: 5
#          successThreshold: 1
#          failureThreshold: 3
#          httpGet:
#            path: /health
#            port: admission
#            scheme: HTTPS
